# Generated by Django 4.2 on 2023-07-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_main', '0002_rename_post_question_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
    ]
