# Generated by Django 4.2 on 2023-07-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_main', '0004_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='category',
        ),
    ]
